### PR TITLE
Create example FHIR resources #8

### PR DESCRIPTION
**Pull request by mozzy11**

### CODE REVIEW

**Comment by mozzy11** [comment]
cc @pmanko

**Comment by mozzy11** [comment]
hi @pmanko 
i can see the build fails because of  
`
Publishing Content Failed: Unable to connect to terminology server. Error = Error fetching the server's capability statement: connect timed out (00:49.0079)` 
The terminology server at http://tx.fhir.org is down

When you look at the build , SUSHI succesfully compiled all my changes and i can run this succesfully locally

I ran the [CI build](https://github.com/I-TECH-UW/emr-lis-ig/runs/2984227779?check_suite_focus=true) on the main repository without my changes and it still failed

**Comment by mozzy11** [comment]
i think it only builds succesfully on a push to the repository

**Comment by mozzy11** [comment]
here is a screenshot of the IG running locally with the example resources i added
image

and published on my repository here https://mozzy11.github.io/IG-PUBLISHER/artifacts.html

**Comment by mozzy11** [comment]
I think the CI build fails because this terminology server at `http://tx.fhir.org  ` is down

**Comment by mozzy11** [comment]
hello @pmanko ,
The terminology server at http://tx.fhir.org  is now up.
i have re-run the jobs and it has passed.
the ci build only fails at the `deploy` step since  it  can only acces the github_token when the PR is merged

**Comment by mozzy11** [comment]
hey @pmanko , any comment on this.
want to pick up another issue

**Comment by pmanko** [comment]
@mozzy11 sounds good - the github actions PR limitation is always a bit annoying -_-

**Comment by pmanko** [comment]
If you push your branch this repo, I can run the action on your branch manually - and possibly the tests won't fail?

**Comment by pmanko** [comment]
so PRs would always be from a I-TECH-UW/emr-lis-ig branch to main.

**Comment by mozzy11** [comment]
the only problem ,is that if i push my PR to a branch , the Ig publisher would still update the `gh-pages` branch hence update the IG

**Pull request merged**
